name: flutter_workbench
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tmcmaster/flutter_workbench/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod:

  widget_tester:
    path: ../widget_tester
#    git:
#      url: https://github.com/tmcmaster/widget_tester.git
  screen_tester:
    path: ../screen_tester
#    git:
#      url: https://github.com/tmcmaster/screen_tester.git
  theme_builder:
    path: ../theme_builder
#    git:
#      url: https://github.com/tmcmaster/theme_builder.git
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
  uuid:
  flutter_riverpod:
  hooks_riverpod:
