name: flutter_workbench
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/tmcmaster/flutter_workbench/blob/main/README.md

environment:
  sdk: ">=2.12.0 <=3.0.5"
  flutter: ">=2.2.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod:
  faker: ^2.0.0
  screenshot:

  widget_tester:
    git:
      url: https://github.com/tmcmaster/widget_tester.git
  screen_tester:
    git:
      url: https://github.com/tmcmaster/screen_tester.git
  prototype_widget:
    git:
      url: https://github.com/tmcmaster/prototype_widget.git
  scaffold_widget:
    git:
      url: https://github.com/tmcmaster/scaffold_widget.git
  theme_builder:
    git:
      url: https://github.com/tmcmaster/theme_builder.git
  widget_examples_tester:
    git:
      url: https://github.com/tmcmaster/widget_examples_tester.git

dependency_overrides:
  widget_tester:
    path: pkgs/widget_tester
  screen_tester:
    path: pkgs/screen_tester
  prototype_widget:
    path: pkgs/prototype_widget
  scaffold_widget:
    path: pkgs/scaffold_widget
  theme_builder:
    path: pkgs/theme_builder
  widget_examples_tester:
    path: pkgs/widget_examples_tester

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  lint:
  test:
  uuid:
  flutter_riverpod:
  hooks_riverpod:
